# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='screenshots_path',
            field=models.FileField(default=None, upload_to='file', verbose_name='\u6d4b\u8bd5\u7ed3\u679c'),
        ),
    ]
