# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_screenshots_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_sum', models.IntegerField(default=0, verbose_name='case\u603b\u548c')),
                ('case_pass_sum', models.IntegerField(default=0, verbose_name='\u901a\u8fc7case\u603b\u548c')),
                ('case_fail_sum', models.IntegerField(default=0, verbose_name='\u5931\u8d25case\u603b\u548c')),
                ('case_date', models.DateTimeField(auto_now_add=True, verbose_name='\u6d4b\u8bd5\u65e5\u671f')),
                ('case_run_time', models.CharField(default='0', max_length=64, verbose_name='\u6d4b\u8bd5\u603b\u8017\u65f6')),
                ('report_uuid', models.CharField(default=None, max_length=256, verbose_name='\u6bcf\u6b21\u8fd0\u884c\u552f\u4e00md5\u6807\u8bc6')),
                ('report_info_create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('report_info_update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
    ]
