# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-03 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_reportinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='screenshots_path',
            field=models.ImageField(default=None, upload_to='upload', verbose_name='\u6d4b\u8bd5\u56fe\u7247'),
        ),
    ]
