# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-31 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20180503_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='case_performance_info',
            field=models.TextField(default=None, max_length=2048, verbose_name='\u6bcf\u6b65\u8fd0\u884c\u7684\u6027\u80fd\u60c5\u51b5\uff0c\u5185\u5b58\u3001cpu\u3001fps'),
        ),
        migrations.AddField(
            model_name='report',
            name='case_step_time',
            field=models.TextField(default=None, max_length=2048, verbose_name='\u6d4b\u8bd5\u6b65\u957f\uff0cjson\u683c\u5f0f'),
        ),
    ]
