# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-31 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20180531_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='case_performance_info',
        ),
    ]
