# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_remove_report_case_performance_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='platform_name',
            field=models.TextField(default='android', max_length=16, verbose_name='\u7cfb\u7edf\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='platform_name',
            field=models.TextField(default='android', max_length=16, verbose_name='\u7cfb\u7edf\u7c7b\u578b'),
        ),
    ]
