# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20180621_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinfo',
            name='platform_env',
            field=models.TextField(default='stage', max_length=16, verbose_name='\u8fd0\u884c\u73af\u5883'),
        ),
    ]
